### PR TITLE
Fix build failure when ntohll and htonll are macros

### LINKED ISSUE #21: Build failed on Mac (x86_64-darwin) due to `ntohll(x)` and `htonll(x)` being `#defined` in `Libsystem`
Partial build log on OfBorg (the CI of [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs)) that demonstrate the error:

```
/nix/store/b0q4wjdw6xwhfsqy8ab106cmhn5xrr8p-bash-5.1-p12/bin/bash ../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I.  -I/nix/store/109pyfb5h9dally7iav62zcsg38i8ydw-dcap-2.47.12-dev/include -DLOCALEDIR=\"/nix/store/iyg74j1agq4iw0pvb1avk93hpfnvzdy4-dcap-2.47.12/share/locale\"   -D_REENTRANT -DLIBC_SYSCALLS -D_GNU_SOURCE -g -O2 -c -o dcap.lo dcap.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I/nix/store/109pyfb5h9dally7iav62zcsg38i8ydw-dcap-2.47.12-dev/include -DLOCALEDIR=\"/nix/store/iyg74j1agq4iw0pvb1avk93hpfnvzdy4-dcap-2.47.12/share/locale\" -D_REENTRANT -DLIBC_SYSCALLS -D_GNU_SOURCE -g -O2 -c dcap.c  -fno-common -DPIC -o .libs/dcap.o
In file included from dcap.c:56:
./dcap_functions.h:43:10: error: expected ')'
uint64_t ntohll(uint64_t x);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./dcap_functions.h:43:10: note: to match this '('
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from dcap.c:56:
./dcap_functions.h:43:10: error: cannot redeclare builtin function '__builtin_constant_p'
uint64_t ntohll(uint64_t x);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./dcap_functions.h:43:10: note: '__builtin_constant_p' is a builtin with type 'int ()'
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
In file included from dcap.c:56:
./dcap_functions.h:47:10: error: expected ')'
uint64_t htonll(uint64_t arg);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
./dcap_functions.h:47:10: note: to match this '('
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
In file included from dcap.c:56:
./dcap_functions.h:47:10: error: cannot redeclare builtin function '__builtin_constant_p'
uint64_t htonll(uint64_t arg);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./dcap_functions.h:43:10: note: '__builtin_constant_p' is a builtin with type 'int ()'
uint64_t ntohll(uint64_t x);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
dcap.c:130:15: error: expected ')'
    uint64_t  htonll(uint64_t);
              ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
dcap.c:130:15: note: to match this '('
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
dcap.c:130:15: error: cannot redeclare builtin function '__builtin_constant_p'
    uint64_t  htonll(uint64_t);
              ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:141:25: note: expanded from macro 'htonll'
#define htonll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./dcap_functions.h:43:10: note: '__builtin_constant_p' is a builtin with type 'int ()'
uint64_t ntohll(uint64_t x);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
dcap.c:133:15: error: expected ')'
    uint64_t  ntohll(uint64_t);
              ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:30: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
                             ^
dcap.c:133:15: note: to match this '('
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:5: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
    ^
dcap.c:133:15: error: cannot redeclare builtin function '__builtin_constant_p'
    uint64_t  ntohll(uint64_t);
              ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
./dcap_functions.h:43:10: note: '__builtin_constant_p' is a builtin with type 'int ()'
uint64_t ntohll(uint64_t x);
         ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/sys/_endian.h:140:25: note: expanded from macro 'ntohll'
#define ntohll(x)       __DARWIN_OSSwapInt64(x)
                        ^
/nix/store/8xkv6d53n2hznyvf1vsyknqz4awj77i7-Libsystem-1238.60.2/include/libkern/_OSByteOrder.h:78:6: note: expanded from macro '__DARWIN_OSSwapInt64'
    (__builtin_constant_p(x) ? __DARWIN_OSSwapConstInt64(x) : _OSSwapInt64(x))
     ^
```

https://logs.nix.ci/?key=nixos/nixpkgs.156282&attempt_id=62c1024b-7e66-4cd7-ae7c-a69ad6d84d6b

Build expression: https://github.com/NixOS/nixpkgs/pull/156282

### PR DESCRIPTION
**Pull request by ShamrockLee**
On Darwin (Mac OS) Libsystem, `ntohll` and `htonll` has been `#define`d as parameterized macro instead of functions

Fix by examine if `ntohll` and `htonll` are `#defined` using `#ifndef`. If defined as macros, the declarations and definitions will be skipped.

Closes #21

### CODE REVIEW

File: src/dcap.c [hunk 1]
```diff
@@ -128,11 +128,15 @@ static int name_invalid(char *);
 static server * url2srv(dcap_url *);
 
 #ifndef HAVE_HTONLL
+#ifndef htonll
```
Comment (kofemann) [inline src/dcap.c:131]: Is it not a better option to write
```
#if !defined(HAVE_HTONLL) && !defined(htonll) 
```

**Review by kofemann — APPROVED** [review]
Thanks a lot for the PR.

File: src/dcap.c (hunk 1 above)
Comment (ShamrockLee) [reply src/dcap.c]: That sounds much better!
Thank you for telling me this.
Updated.

**Review by kofemann — CHANGES_REQUESTED** [review]
Well, this is of course not relevant for OSX, however for completness you should update the src/dcap.c as well, where the custom implementations of those functions are defined:

```C
#ifndef HAVE_NTOHLL
    uint64_t
    ntohll(uint64_t x)
    {
    #ifdef I_AM_LITTLE_ENDIAN
        return  ((((uint64_t)htonl(x)) << 32) + htonl(x >> 32));
    #else
        return x;
    #endif /* I_AM_LITTLE_ENDIAN */
    }
#endif /* HAVE_NTOHLL */

#ifndef HAVE_HTONLL
    uint64_t
    htonll(uint64_t arg)
    {
        return ntohll(arg);
    }
#endif /* HAVE_HTONLL */

```

**Comment by ShamrockLee** [comment]
Updated.

BTW, why do we need to re-declare `htonll()` and `ntohll()` in `dcap.c`, given that they are declared inside `dcap_functions.h`?

**Comment by kofemann** [comment]
Thanks for the update. Indeed, the extra declaration in dcap.c looks redundant.

**Comment by ShamrockLee** [comment]
The redundant declaration has been removed.
